- *Fields:* Backend Engineering, Full Stack Engineering, Systems Architecture, Cloud Computing and Architecture (AWS), AI Engineering (LLMs and ML models), DevOps.
- *Technologies*: Typescript, Node.js, React, Java, Python, AWS, SQL (Postgres, SQLite), NoSQL (DynamoDB, Apache Cassandra), Docker, C, C++, UNIX.
